Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: C:/Users/ASUS/AppData/Local/Programs/Python/Python38/Input2.uas.py =
=====================================
    MESIN PENCARIAM DATA
==================================
Masukan NIP/ KODE karyawan :k001

Traceback (most recent call last):
  File "C:/Users/ASUS/AppData/Local/Programs/Python/Python38/Input2.uas.py", line 35, in <module>
    DATA = data [NIP]
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ASUS/AppData/Local/Programs/Python/Python38/Input2.uas.py", line 59, in <module>
    except keyError :
NameError: name 'keyError' is not defined
>>> 